"""
Pydantic models for AutoDoc Agent.
Defines schemas for API request/response, task plans, and section content.
"""

from pydantic import BaseModel, Field


# ── API Request / Response ──────────────────────────────────────────────────

class AgentRequest(BaseModel):
    """Incoming request to the agent."""
    request: str = Field(
        ...,
        min_length=1,
        description="Natural language request describing the document to generate.",
        json_schema_extra={"examples": [
            "Create meeting minutes for a project kickoff meeting between engineering and the client for a new CRM system."
        ]}
    )


class AgentResponse(BaseModel):
    """Response returned by the agent after document generation."""
    document_type: str = Field(
        ..., description="The type of document the agent inferred."
    )
    plan: list[str] = Field(
        ..., description="The task plan the agent generated for itself."
    )
    assumptions: list[str] = Field(
        default_factory=list,
        description="Assumptions the agent made to fill gaps in the request."
    )
    file_path: str = Field(
        ..., description="Path to the generated .docx file."
    )


# ── Planning Models ─────────────────────────────────────────────────────────

class PlanStep(BaseModel):
    """A single step in the agent's task plan."""
    step_number: int = Field(..., description="Order of this step.")
    action: str = Field(..., description="What the agent will do in this step.")
    section_title: str | None = Field(
        default=None,
        description="Title of the document section this step produces, if any."
    )


class AgentPlan(BaseModel):
    """Structured plan generated by the LLM planner."""
    document_type: str = Field(
        ..., min_length=1,
        description="Inferred document type (e.g. 'Meeting Minutes', 'Status Report')."
    )
    sections: list[str] = Field(
        ..., min_length=1,
        description="Ordered list of section titles to generate."
    )
    assumptions: list[str] = Field(
        default_factory=list,
        description="Assumptions made due to missing information."
    )
    steps: list[PlanStep] = Field(
        default_factory=list,
        description="Detailed step-by-step execution plan."
    )


# ── Execution Models ────────────────────────────────────────────────────────

class SectionContent(BaseModel):
    """Content generated for a single document section."""
    title: str = Field(..., description="Section heading.")
    content: str = Field(
        default="", description="Paragraph / narrative content for the section."
    )
    table_data: list[dict] | None = Field(
        default=None,
        description="Structured table data (list of row dicts), if applicable."
    )
